// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwpahpicznlwlopzzzns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13cGFocGljem5sd2xvcHp6em5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDQ2MTcsImV4cCI6MjA1OTk4MDYxN30.bHw8MBXoJjtfy7p0Z6R_A5lXQmEXAJLkRL_LyLLquUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);